// Code generated by protoc-gen-go-idl. DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"github.com/tenz-io/gokit/genproto"
)

func init(){
{{range .Messages}}
	genproto.Register(&{{.Name}}{})
{{end}}
}

{{range .Messages}}
func (x *{{.Name}}) Validate (ctx context.Context) error {
	return genproto.Validate(x)
}
{{end}}

