// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: custom/options/authz.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Auth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Role:
	//
	//	*Auth_Anonymous
	//	*Auth_User
	//	*Auth_Admin
	Role isAuth_Role `protobuf_oneof:"role"`
}

func (x *Auth) Reset() {
	*x = Auth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_custom_options_authz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_custom_options_authz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_custom_options_authz_proto_rawDescGZIP(), []int{0}
}

func (m *Auth) GetRole() isAuth_Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (x *Auth) GetAnonymous() int32 {
	if x, ok := x.GetRole().(*Auth_Anonymous); ok {
		return x.Anonymous
	}
	return 0
}

func (x *Auth) GetUser() int32 {
	if x, ok := x.GetRole().(*Auth_User); ok {
		return x.User
	}
	return 0
}

func (x *Auth) GetAdmin() int32 {
	if x, ok := x.GetRole().(*Auth_Admin); ok {
		return x.Admin
	}
	return 0
}

type isAuth_Role interface {
	isAuth_Role()
}

type Auth_Anonymous struct {
	Anonymous int32 `protobuf:"varint,1,opt,name=anonymous,proto3,oneof"`
}

type Auth_User struct {
	User int32 `protobuf:"varint,2,opt,name=user,proto3,oneof"`
}

type Auth_Admin struct {
	Admin int32 `protobuf:"varint,4,opt,name=admin,proto3,oneof"`
}

func (*Auth_Anonymous) isAuth_Role() {}

func (*Auth_User) isAuth_Role() {}

func (*Auth_Admin) isAuth_Role() {}

var file_custom_options_authz_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Auth)(nil),
		Field:         50001,
		Name:          "custom.options.auth",
		Tag:           "bytes,50001,opt,name=auth",
		Filename:      "custom/options/authz.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional custom.options.Auth auth = 50001;
	E_Auth = &file_custom_options_authz_proto_extTypes[0]
)

var File_custom_options_authz_proto protoreflect.FileDescriptor

var file_custom_options_authz_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c,
	0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x09, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d,
	0x6f, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x09, 0x61, 0x6e, 0x6f,
	0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x05,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x3a, 0x4a, 0x0a, 0x04,
	0x61, 0x75, 0x74, 0x68, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x6e, 0x7a, 0x2d, 0x69, 0x6f, 0x2f, 0x67,
	0x6f, 0x6b, 0x69, 0x74, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3b,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_custom_options_authz_proto_rawDescOnce sync.Once
	file_custom_options_authz_proto_rawDescData = file_custom_options_authz_proto_rawDesc
)

func file_custom_options_authz_proto_rawDescGZIP() []byte {
	file_custom_options_authz_proto_rawDescOnce.Do(func() {
		file_custom_options_authz_proto_rawDescData = protoimpl.X.CompressGZIP(file_custom_options_authz_proto_rawDescData)
	})
	return file_custom_options_authz_proto_rawDescData
}

var file_custom_options_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_custom_options_authz_proto_goTypes = []interface{}{
	(*Auth)(nil),                       // 0: custom.options.Auth
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_custom_options_authz_proto_depIdxs = []int32{
	1, // 0: custom.options.auth:extendee -> google.protobuf.MethodOptions
	0, // 1: custom.options.auth:type_name -> custom.options.Auth
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_custom_options_authz_proto_init() }
func file_custom_options_authz_proto_init() {
	if File_custom_options_authz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_custom_options_authz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_custom_options_authz_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Auth_Anonymous)(nil),
		(*Auth_User)(nil),
		(*Auth_Admin)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_custom_options_authz_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_custom_options_authz_proto_goTypes,
		DependencyIndexes: file_custom_options_authz_proto_depIdxs,
		MessageInfos:      file_custom_options_authz_proto_msgTypes,
		ExtensionInfos:    file_custom_options_authz_proto_extTypes,
	}.Build()
	File_custom_options_authz_proto = out.File
	file_custom_options_authz_proto_rawDesc = nil
	file_custom_options_authz_proto_goTypes = nil
	file_custom_options_authz_proto_depIdxs = nil
}
