version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: "dbtracker-mysql"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=trackertest_db
      - MYSQL_ROOT_PASSWORD=mysql_123
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
