// Code generated by protoc-gen-go-idl. DO NOT EDIT.
package v1

import (
	"context"
	"github.com/tenz-io/gokit/genproto"
)

func init() {

	genproto.Register(&LoginRequest{})

	genproto.Register(&LoginResponse{})

	genproto.Register(&HelloRequest{})

	genproto.Register(&HelloResponse{})

	genproto.Register(&GetImageRequest{})

	genproto.Register(&GetImageResponse{})

	genproto.Register(&UploadImageRequest{})

	genproto.Register(&UploadImageResponse{})

}

func (x *LoginRequest) Validate(ctx context.Context) error {
	return genproto.Validate(x)
}

func (x *LoginRequest) validateRule() error {
	return genproto.Validate(x)
}

func (x *LoginResponse) Validate(ctx context.Context) error {
	return genproto.Validate(x)
}

func (x *HelloRequest) Validate(ctx context.Context) error {
	return genproto.Validate(x)
}

func (x *HelloResponse) Validate(ctx context.Context) error {
	return genproto.Validate(x)
}

func (x *GetImageRequest) Validate(ctx context.Context) error {
	return genproto.Validate(x)
}

func (x *GetImageResponse) Validate(ctx context.Context) error {
	return genproto.Validate(x)
}

func (x *UploadImageRequest) Validate(ctx context.Context) error {
	return genproto.Validate(x)
}

func (x *UploadImageResponse) Validate(ctx context.Context) error {
	return genproto.Validate(x)
}
