package main

import (
	"github.com/tenz-io/gokit/genproto/go/custom/idl"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	contextPkg  = protogen.GoImportPath("context")
	genprotoPkg = protogen.GoImportPath("github.com/tenz-io/gokit/genproto")
	idlPkg      = protogen.GoImportPath("github.com/tenz-io/gokit/genproto/go/custom/idl")
	protoPkg    = protogen.GoImportPath("google.golang.org/protobuf/proto")
)

func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Messages) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_validate.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by github.com/tenz-io/gokit/protoc-gen-go-validator. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the github.com/tenz-io/gokit/protoc-gen-go-validator package it is being compiled against.")
	g.P("// ", contextPkg.Ident(""), genprotoPkg.Ident(""))
	g.P("// ", idlPkg.Ident(""), protoPkg.Ident(""))
	g.P()

	genMessages(gen, file, g)

	return g
}

func genMessages(_ *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	msgTpl := &messageTemplate{
		Messages: []messageData{},
	}

	for _, msg := range file.Messages {
		deprecated := msg.Desc.Options().(*descriptorpb.MessageOptions).GetDeprecated()
		msgData := messageData{
			deprecated: deprecated,
			Name:       string(msg.Desc.Name()),
			Fields:     msgFields(msg),
		}
		msgTpl.Messages = append(msgTpl.Messages, msgData)
	}

	g.P(msgTpl.execute())
}

func msgFields(msg *protogen.Message) []fieldData {
	var fields []fieldData
	for _, field := range msg.Fields {
		options := proto.GetExtension(field.Desc.Options(), idl.E_Field)
		if options == nil {
			continue
		}
		fieldOpts, ok := options.(*idl.Field)
		if !ok {
			continue
		}

		fields = append(fields, fieldData{
			Name:        field.GoName,
			IntField:    fieldOpts.GetInt(),
			StringField: fieldOpts.GetStr(),
			BytesField:  fieldOpts.GetBytes(),
			ArrayField:  fieldOpts.GetArray(),
		})
	}

	return fields
}
