// Code generated by github.com/tenz-io/gokit/protoc-gen-go-validator. DO NOT EDIT.

package v1

import (
	context "context"
	genproto "github.com/tenz-io/gokit/genproto"
	idl "github.com/tenz-io/gokit/genproto/go/custom/idl"
	proto "google.golang.org/protobuf/proto"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the github.com/tenz-io/gokit/protoc-gen-go-validator package it is being compiled against.
// context.genproto.
// idl.proto.

func (x *LoginRequest) Validate(_ context.Context) error {
	return genproto.ValidateMessage(x.ValidateRule(), x)
}

func (x *LoginRequest) ValidateRule() genproto.FieldRules {
	return genproto.FieldRules{

		"Username": &idl.Field{
			Str: &idl.StringField{
				Required: proto.Bool(true),
				NotBlank: proto.Bool(true),
				MinLen:   proto.Int64(2),
				MaxLen:   proto.Int64(64),
			},
		},

		"Password": &idl.Field{
			Str: &idl.StringField{
				Required: proto.Bool(true),
				NotBlank: proto.Bool(true),
				MinLen:   proto.Int64(6),
				MaxLen:   proto.Int64(64),
			},
		},
	}
}

func (x *LoginResponse) Validate(_ context.Context) error {
	return genproto.ValidateMessage(x.ValidateRule(), x)
}

func (x *LoginResponse) ValidateRule() genproto.FieldRules {
	return genproto.FieldRules{

		"AccessToken": &idl.Field{},

		"RefreshToken": &idl.Field{},
	}
}

func (x *HelloRequest) Validate(_ context.Context) error {
	return genproto.ValidateMessage(x.ValidateRule(), x)
}

func (x *HelloRequest) ValidateRule() genproto.FieldRules {
	return genproto.FieldRules{

		"Name": &idl.Field{
			Str: &idl.StringField{
				Default:  proto.String("goer"),
				Required: proto.Bool(true),
				NotBlank: proto.Bool(true),
				MinLen:   proto.Int64(2),
				MaxLen:   proto.Int64(64),
			},
		},
	}
}

func (x *HelloResponse) Validate(_ context.Context) error {
	return genproto.ValidateMessage(x.ValidateRule(), x)
}

func (x *HelloResponse) ValidateRule() genproto.FieldRules {
	return genproto.FieldRules{

		"Message": &idl.Field{},
	}
}

func (x *GetImageRequest) Validate(_ context.Context) error {
	return genproto.ValidateMessage(x.ValidateRule(), x)
}

func (x *GetImageRequest) ValidateRule() genproto.FieldRules {
	return genproto.FieldRules{

		"Key": &idl.Field{
			Str: &idl.StringField{
				Required: proto.Bool(true),
				NotBlank: proto.Bool(true),
				MaxLen:   proto.Int64(64),
			},
		},

		"Width": &idl.Field{
			Int: &idl.IntField{
				Default: proto.Int64(640),
				Gt:      proto.Int64(0),
				Lte:     proto.Int64(1024),
			},
		},

		"Height": &idl.Field{
			Int: &idl.IntField{
				Default: proto.Int64(480),
				Gt:      proto.Int64(0),
				Lte:     proto.Int64(1024),
			},
		},
	}
}

func (x *GetImageResponse) Validate(_ context.Context) error {
	return genproto.ValidateMessage(x.ValidateRule(), x)
}

func (x *GetImageResponse) ValidateRule() genproto.FieldRules {
	return genproto.FieldRules{

		"File": &idl.Field{},
	}
}

func (x *UploadImageRequest) Validate(_ context.Context) error {
	return genproto.ValidateMessage(x.ValidateRule(), x)
}

func (x *UploadImageRequest) ValidateRule() genproto.FieldRules {
	return genproto.FieldRules{

		"Image": &idl.Field{
			Bytes: &idl.BytesField{
				Required: proto.Bool(true),
				MinLen:   proto.Int64(1),
				MaxLen:   proto.Int64(1048576),
			},
		},

		"Category": &idl.Field{
			Str: &idl.StringField{
				Default:  proto.String("post"),
				Required: proto.Bool(true),
				NotBlank: proto.Bool(true),
				In: []string{
					"avatar",
					"background",
					"post",
				},
			},
		},
	}
}

func (x *UploadImageResponse) Validate(_ context.Context) error {
	return genproto.ValidateMessage(x.ValidateRule(), x)
}

func (x *UploadImageResponse) ValidateRule() genproto.FieldRules {
	return genproto.FieldRules{

		"Key": &idl.Field{},
	}
}

func (x *UpdateProgressRequest) Validate(_ context.Context) error {
	return genproto.ValidateMessage(x.ValidateRule(), x)
}

func (x *UpdateProgressRequest) ValidateRule() genproto.FieldRules {
	return genproto.FieldRules{

		"Progress": &idl.Field{
			Float: &idl.FloatField{
				Default:  proto.Float64(0.7),
				Required: proto.Bool(true),
				Gte:      proto.Float64(0),
				Lte:      proto.Float64(1),
			},
		},

		"CatIds": &idl.Field{
			Array: &idl.ArrayField{
				MinItems: proto.Int64(1),
				MaxItems: proto.Int64(10),
				Item: &idl.ItemField{
					Int: &idl.IntField{
						Gt:  proto.Int64(1000),
						Lte: proto.Int64(5000),
					},
				},
			},
		},
	}
}

func (x *UpdateProgressResponse) Validate(_ context.Context) error {
	return genproto.ValidateMessage(x.ValidateRule(), x)
}

func (x *UpdateProgressResponse) ValidateRule() genproto.FieldRules {
	return genproto.FieldRules{

		"Progress": &idl.Field{},
	}
}
