// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: custom/common/authz.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ANONYMOUS Role = 0
	Role_ADMIN     Role = 1
	Role_USER      Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ANONYMOUS",
		1: "ADMIN",
		2: "USER",
	}
	Role_value = map[string]int32{
		"ANONYMOUS": 0,
		"ADMIN":     1,
		"USER":      2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_custom_common_authz_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_custom_common_authz_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_custom_common_authz_proto_rawDescGZIP(), []int{0}
}

type AuthType int32

const (
	AuthType_WEB  AuthType = 0 // web page, verify by cookie
	AuthType_REST AuthType = 1 // restful api, verify by token
)

// Enum value maps for AuthType.
var (
	AuthType_name = map[int32]string{
		0: "WEB",
		1: "REST",
	}
	AuthType_value = map[string]int32{
		"WEB":  0,
		"REST": 1,
	}
)

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_custom_common_authz_proto_enumTypes[1].Descriptor()
}

func (AuthType) Type() protoreflect.EnumType {
	return &file_custom_common_authz_proto_enumTypes[1]
}

func (x AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthType.Descriptor instead.
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return file_custom_common_authz_proto_rawDescGZIP(), []int{1}
}

type Auth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role Role     `protobuf:"varint,1,opt,name=role,proto3,enum=custom.common.Role" json:"role,omitempty"`
	Type AuthType `protobuf:"varint,2,opt,name=type,proto3,enum=custom.common.AuthType" json:"type,omitempty"`
}

func (x *Auth) Reset() {
	*x = Auth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_custom_common_authz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_custom_common_authz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_custom_common_authz_proto_rawDescGZIP(), []int{0}
}

func (x *Auth) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ANONYMOUS
}

func (x *Auth) GetType() AuthType {
	if x != nil {
		return x.Type
	}
	return AuthType_WEB
}

var file_custom_common_authz_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Auth)(nil),
		Field:         50001,
		Name:          "custom.common.auth",
		Tag:           "bytes,50001,opt,name=auth",
		Filename:      "custom/common/authz.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional custom.common.Auth auth = 50001;
	E_Auth = &file_custom_common_authz_proto_extTypes[0]
)

var File_custom_common_authz_proto protoreflect.FileDescriptor

var file_custom_common_authz_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x04,
	0x41, 0x75, 0x74, 0x68, 0x12, 0x27, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x2b, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x2a, 0x0a, 0x04, 0x52, 0x6f,
	0x6c, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x4e, 0x4f, 0x4e, 0x59, 0x4d, 0x4f, 0x55, 0x53, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x55, 0x53, 0x45, 0x52, 0x10, 0x02, 0x2a, 0x1d, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x45, 0x42, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52,
	0x45, 0x53, 0x54, 0x10, 0x01, 0x3a, 0x49, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x1e, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68,
	0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74,
	0x65, 0x6e, 0x7a, 0x2d, 0x69, 0x6f, 0x2f, 0x67, 0x6f, 0x6b, 0x69, 0x74, 0x2f, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_custom_common_authz_proto_rawDescOnce sync.Once
	file_custom_common_authz_proto_rawDescData = file_custom_common_authz_proto_rawDesc
)

func file_custom_common_authz_proto_rawDescGZIP() []byte {
	file_custom_common_authz_proto_rawDescOnce.Do(func() {
		file_custom_common_authz_proto_rawDescData = protoimpl.X.CompressGZIP(file_custom_common_authz_proto_rawDescData)
	})
	return file_custom_common_authz_proto_rawDescData
}

var file_custom_common_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_custom_common_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_custom_common_authz_proto_goTypes = []interface{}{
	(Role)(0),                          // 0: custom.common.Role
	(AuthType)(0),                      // 1: custom.common.AuthType
	(*Auth)(nil),                       // 2: custom.common.Auth
	(*descriptorpb.MethodOptions)(nil), // 3: google.protobuf.MethodOptions
}
var file_custom_common_authz_proto_depIdxs = []int32{
	0, // 0: custom.common.Auth.role:type_name -> custom.common.Role
	1, // 1: custom.common.Auth.type:type_name -> custom.common.AuthType
	3, // 2: custom.common.auth:extendee -> google.protobuf.MethodOptions
	2, // 3: custom.common.auth:type_name -> custom.common.Auth
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_custom_common_authz_proto_init() }
func file_custom_common_authz_proto_init() {
	if File_custom_common_authz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_custom_common_authz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_custom_common_authz_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_custom_common_authz_proto_goTypes,
		DependencyIndexes: file_custom_common_authz_proto_depIdxs,
		EnumInfos:         file_custom_common_authz_proto_enumTypes,
		MessageInfos:      file_custom_common_authz_proto_msgTypes,
		ExtensionInfos:    file_custom_common_authz_proto_extTypes,
	}.Build()
	File_custom_common_authz_proto = out.File
	file_custom_common_authz_proto_rawDesc = nil
	file_custom_common_authz_proto_goTypes = nil
	file_custom_common_authz_proto_depIdxs = nil
}
